### PR TITLE
Add 'speed' of counter and 'delay' for each colums.

### PR DESCRIPTION
**Pull request by tuanngocptn**
Hello @almond-bongbong.

I just added the speed and delay properties:

- The `speed` property help us control the counter speed. for make that more smooth.
- The `delay` property will set the delay for each columns when running.

Please check this PR and merge them ASAP. 

P/S: Btw, I added the contributors part into the readme.

Thank and regard.

### CODE REVIEW

**Review by almond-bongbong — CHANGES_REQUESTED** [review]
Thank you for taking the time to create this PR. The speed and delay options appear to be intuitive and useful; however, there are a few additional considerations that need to be addressed.

- The change in the default number of dummyCharacters could alter the existing user experience. Previously, the default value generated 5 dummyCharacters, whereas the updated code generates 6, resulting in a perceived increase in speed. This change might affect the current user experience, so it would be preferable to maintain the same experience by keeping the default values consistent.

- I agree that using speed and duration is much more intuitive than the previous method of adjusting speed and animation duration with duration and dummyCharacterCount. However, since duration is now used to calculate the number of dummyCharacters, this introduces different behavior compared to the original implementation. As a result, this change may require a major update and might necessitate re-education and guidance for existing users. This aspect warrants further consideration.

- When duration is set to around 5, there is an issue where the value changes prematurely starting from the second change. It would be beneficial to review the time calculation logic at line 125 in the Slot component to address this.


May-20-2024 23-49-26

**Comment by tuanngocptn** [comment]
Hello @almond-bongbong, 

Thanks for your comment.

- For the first problem, I just check again and decrease the default speed from 1.5 second to 1.4 second. After that, the animation become smoother like the previous version.
- hmmm, okay I think after this change. Maybe we need to make other version that have a lot of change. After that we need to have the new announcement to all of users for changing, updating, using the new version. But we need do that, because the new way is easier for using.
- For the last problem, Can you show me more detail, because I don't have the same you problem. 


https://github.com/almond-bongbong/react-slot-counter/assets/22292704/8c98d4e8-bf5e-4cd0-8de9-0edc641d64de


Thanks

**Comment by almond-bongbong** [comment]
Thank you for your insights!

- I agree with your opinion that this is a better approach. I will seriously consider a major update.
- Here is my example for the third question:

```
const [value3, setValue3] = React.useState(random(100, 999));

---

<SlotCounter value={value3} duration={3} />

<button
    type="button"
    className="example-button"
    onClick={() => setValue3(random(100, 999))}
>
    Play
</button>

```

Thank you again for your feedback!

**Comment by baronha** [comment]
Hi @almond-bongbong I fixed this issue for value changes prematurely starting

**Comment by tuanngocptn** [comment]
oh cool. thanks you, my friend @baronha

**Comment by baronha** [comment]
> oh cool. thanks you, my friend @baronha

oh. No problem bruh!

**Comment by almond-bongbong** [comment]
@baronha @tuanngocptn Thank you both for your contributions. I believe this is a great update from the developer experience perspective. Also, thanks for adding a section in the README to acknowledge contributors.

Although I cannot invest much time due to my full-time job, I will dedicate all my available time to check for side effects and review this update. I plan to include this in the next major update (probably 3.0.0). Thank you for your patience, and while I can't promise an immediate update, I am very positive about it.

Thank you for your contributions, and please wait a bit longer!

**Review by almond-bongbong — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
