### PR TITLE
feat: add prop to support reversed animation

### PR DESCRIPTION
**Pull request by vh-x**
This PR introduces a new prop for reversed animation. When set to true, the slot machine animation will render from right to left instead of the default left to right.

- Added reversed prop to Props interface
- Updated the animation logic to respect the reversed prop
- Default value for reversed is false

### CODE REVIEW

**Comment by almond-bongbong** [comment]
Thank you for your contribution. I will review the changes and provide feedback soon. Thank you.

**Comment by almond-bongbong** [comment]
First and foremost, I sincerely apologize for the delay in reviewing this PR. 

Thank you for adding this valuable feature. The ability to control the animation direction is an excellent improvement that will enhance the component's flexibility.

If I may, I'd like to respectfully suggest considering some alternatives for the `reversed` prop name:

1. The term `reversed` might be slightly ambiguous, as it's not immediately clear what aspect is being reversed.

2. To further improve code readability and maintainability, perhaps we could consider a more explicit boolean prop name. Here are a few suggestions for your consideration:
   - `animateFromEnd`: boolean
   - `reverseAnimationOrder`: boolean
   - `startFromLastDigit`: boolean

These alternatives aim to more clearly convey the prop's purpose while maintaining its boolean nature.

Additionally, it would be greatly appreciated if you could update the props list table in the README to include this new prop. This will ensure that the documentation remains comprehensive and up-to-date for all users.

Once again, thank you for this great enhancement. With a slightly more descriptive prop name and updated documentation, it will be an excellent addition to the component.

**Comment by vh-x** [comment]
Thank you for your feedback!

I agree with your point, and I have renamed the prop to `startFromLastDigit` as suggested. 

The README has also been updated accordingly. I appreciate your kind words and guidance, and I’m glad this feature will add value to the component.

**Comment by almond-bongbong** [comment]
Thank you for your contribution

**Review by almond-bongbong — APPROVED** [review]

**Pull request merged**
